In [4]:
import  numpy as np

In [5]:
arr = np.array([1, 2, 3])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
arr = np.array([1, 2, 3])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
arr = np.array([1, 2, 3])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
arr = np.array([1, 2, 3])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [9]:
arr = np.array([1, 2, 3])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [10]:
arr = np.array([1, 2, 3])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
np.random.rand(3, 2)

array([[0.37292392, 0.37687162],
       [0.24706303, 0.48271705],
       [0.13138511, 0.57684619]])

In [11]:
arr = np.array([1, 2, 3])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
np.random.randn(3, 2)

array([[-0.24670843,  0.53356502],
       [-0.12368861, -0.83578433],
       [ 0.27458441, -0.10754657]])

In [12]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)

(2, 3)


In [13]:
print(arr.ndim)

2


In [14]:
print(arr.size)

6


In [16]:
print(arr.dtype)

int64


In [17]:
a = np.array([1, 2, 3])

b = np.array([4, 5, 6])
a + b

array([5, 7, 9])

In [18]:
a * b

array([ 4, 10, 18])

In [19]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [20]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [21]:
A @ B

array([[19, 22],
       [43, 50]])

In [22]:
arr = np.array([1, 2, 3, 4])
arr.sum()

np.int64(10)

In [23]:
arr.mean()

np.float64(2.5)

In [24]:
arr.max()

np.int64(4)

In [25]:
arr.min()

np.int64(1)

In [26]:
arr.std()

np.float64(1.118033988749895)

In [27]:
arr = np.array([1, 2, 3, 4, 5])
arr[0]

np.int64(1)

In [28]:
arr[1:4]

array([2, 3, 4])

In [29]:
arr[::2]

array([1, 3, 5])

In [30]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr[0, 1]

np.int64(2)

In [31]:
arr[:, 1]

array([2, 5])

In [32]:
arr[1, :2]

array([4, 5])

In [36]:
arr = np.array([1, 2, 3, 4, 5])
mask = arr > 3
arr[mask]

array([4, 5])

In [37]:
arr = np.arange(6)
arr.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [38]:
a = np.array([1, 2])
b = np.array([3, 4])
np.concatenate((a, b))

array([1, 2, 3, 4])

In [39]:
np.vstack((a, b))

array([[1, 2],
       [3, 4]])

In [40]:
np.hstack((a, b))

array([1, 2, 3, 4])

In [41]:
a = np.array([1, 2, 3])
a + 5 # [6, 7, 8]

array([6, 7, 8])

In [43]:
np.save('array.npy',arr)

In [44]:
loaded_arr = np.load('array.npy')